### ISSUE TITLE
parallel processing

### ISSUE THREAD

**Issue by aogier** [jsvine/markovify#172]
Dear author(s), I'm currently sit here waiting for a model to generate so I'll take a minute sharing a question and an idea.

Given `A=B+C`, is `Text(A) = combine([Text(B), Text(C)])` true? (unsure on that, because I'm a donkey).

If combine() does indeed work that way, it should be easy to exploit multiprocessing by splitting input to a pool of workers and then combine them at the end. It would help a lot when working on larger datasets, and I could contribute it (because I'm also a monkey :monkey: ).

What do you think? Thank you, regards!

**Comment by jsvine** [comment]
Hi @aogier, and thanks for opening this issue! I think adding an *option* to use multiprocessing is a solid suggestion. Although `combine()` does indeed work that way, there is one tricky part to make sure it works 100% faithfully, which is to ensure that the split between `B` and `C` is selected carefully, so that it occurs only at natural divisions in the corpus. (E.g., in between two sentences, in the case of a standard text.)

**Comment by aogier** [comment]
Hi, thank you for your feedback. Your point about splitting made me realise I was a bit naive about the possible implementation, so after a bit profiling I found how to put this feature further from users, ie. without changing any interface/ease of use they have as of today.
The promising part is the `filter`/`map` pipeline in [`markovify.Text.generate_corpus`](https://github.com/jsvine/markovify/blob/74696e331d7daf1fe3accf46a762193057c243cb/markovify/text.py#L159), so ATM I'm working on a first PoC which multiprocess that while keeping it easy on memory as it currently is, even though multiprocessing will probably require a bit more of it but we will see.

Hope to continue this discourse on a PR soon, thanks!

**Comment by jsvine** [comment]
@aogier Thanks for the nudge! I'll try to prioritize this and getting you feedback soon.

**Comment by aogier** [comment]
forking away, thank you for all the nothing :P
