### ISSUE TITLE
Make Short Sentence Word Delimited

### ISSUE THREAD

**Issue by stanzheng** [jsvine/markovify#40]
It seems like it would make the method more intuitive if we were able to change this to word delimited compared to char delimited.

Often it comes back as `None` in my experiments with my limited corpus, but it should be guaranteed to come back as a value if it's word delimited and feel a bit more intuitive.

https://github.com/jsvine/markovify/blob/master/markovify/text.py#L130-L139

**Comment by jsvine** [comment]
Hi @stanzheng, and thanks for the note! Responses below.

> It seems like it would make the method more intuitive if we were able to change this to word delimited compared to char delimited.

The method limits the number of characters primarily because of the widespread use of markov chains to build Twitter bots. 

That said, I'd be open to modifying the method slightly so that users could pass a `max_words=` kwarg if they preferred to limit by word count. 

> Often it comes back as None in my experiments with my limited corpus, but it should be guaranteed to come back as a value if it's word delimited and feel a bit more intuitive.

Perhaps I'm misunderstanding your observation, but I don't think this method would be any less likely to return `None` if it tracked word counts rather than character lengths. (The current method does not force a sentence to be exactly `char_limit` characters, but instead a maximum of `char_limit` characters.) What might I be misunderstanding?

**Comment by stanzheng** [comment]
That makes total sense about the character limit in regard to Twitter and how that function handles it.

I'm new to Markov chains and I should have studied the implementation a bit closer. I see now the retry passes `None` if in 10 chain generations if it's too large char-wise. I think what I actually want is a modification of `make_sentance` with a variation that I can then walk up to a certain point (num of words) and stop. 

Here is what I was attempting to compare in code but I know that now it's because the max_retries is exceeded. Should the `DEFAULT_TRIES` be configurable as a default param or should that be handled in user code?

Thanks for the interesting lib.
```
        chain1 = []
        chain2 = []
        for i in range(100):
            c1 = name_model.make_short_sentence(100)
            c2 = name_model.make_sentence()
            if c1:
                chain1.append(c1)
            if c2:
                chain2.append(c2)

        print('Chain1: ', len(chain1))
        print('Chain2: ', len(chain2))
        # 100
        # 71 
```
