### ISSUE TITLE
The method make_sentence_with_start() seems like it only finds sentences that start with the seed.

### ISSUE THREAD

**Issue by rmcintyre319** [jsvine/markovify#48]
It seems like make_sentence_with_start() is only looking through the corpus for lines/sentences that begin with the string you pass it, as opposed to searching the entire sentence for that word. For instance, I can add "I like to program with markov chains", and then trying to make_sentence_with_start("markov") will fail. However, if the log contains "markov chains are neat", then the chain will succeed, because the sentence begins with markov. Is there any way to make it so that it searches the entire sentence for the word, instead of just the beginning? For reference, here's the method we're using to build a markov chain: 
```
def markovstring(prefix=None):
    with open ("log.txt", 'r', encoding='utf8') as file:
        text = file.read()
        text_model = markovify.NewlineText(text)
        if prefix is not None:
            try:
                message = text_model.make_sentence_with_start(prefix)
                for x in range(10):
                    message = text_model.make_sentence_with_start(prefix)
                if message is not None:
                    return message
                else:
                    return "Cannot create a chain with that string " + prefix
            except:
                return "Cannot create a chain with the string " + prefix
        else:
            message = text_model.make_sentence()
            while message is None:
                message = text_model.make_sentence()
            return message
```

**Comment by jsvine** [comment]
Hi Riley, and thanks for submitting this issue. You're understanding the situation correctly. 

What you're running into is to be expected, if not optimal: If you pass a `prefix` that contains fewer words than the model's `state_size` — e.g., `"markov"` when `text_model.state_size == 2` — the `.make_sentence_with_start` method only looks at the beginning of sentences. 

The underlying reason is that `text_model.chain.move(...)` — on which `text_model.make_sentence_with_start(...)` is ultimately based — expects a tuple of `state_size` length. Currently, `.move` doesn't know how to handle shorter tuples, which represent many possible states (e.g., `("markov", *, *)`) rather than a specific state (e.g., `("markov", "chains", "are")`). 

It seems like a worthwhile goal to add shorter-tuple functionality to `.move`, which would also make it possible to do the thing you want to do.

**Comment by dcavalcante** [comment]
+1 for this feature!

**Comment by danmayer** [comment]
I have submitted a PR that implements this feature... I chose to add a new method `make_sentence_with_words`vs extending the existing method `make_sentence_with_start`, but I am open to any feedback.

https://github.com/jsvine/markovify/pull/80

**Comment by danmayer** [comment]
let me know @jsvine / @rmcintyre319

**Comment by amirouche** [comment]
What is the status of this ticket? It was merged. What requires to be done?

**Comment by rmcintyre319** [comment]
If the PR was merged, looks like the situation was resolved. I'll close the ticket.
