### ISSUE TITLE
Shouldn't loading in a previous model take far less time?

### ISSUE THREAD

**Issue by Abhishaike** [jsvine/markovify#56]
As in, when I do this: 

```
corpus = open('sherlock.txt').read()
corpus = re.sub( '\s+', ' ', corpus ).strip()
text_model = POSifiedText(corpus, state_size=4)
model1_json = text_model.chain.to_json()
with open(data.txt, 'w') as outfile:  
    json.dump(model1_json, outfile)

with open('data.txt') as json_file:  
	model2_json = json.load(json_file)
```
and....
```
NEW1_MODEL = POSifiedText.from_json(model2_json)
NEW2_MODEL = POSifiedText(corpus, state_size=4)
```

How come the NEW1_MODEL takes the exact same amount of time to generate as opposed to the NEW2_MODEL? Shouldn't it take far less time, because it's using an already generated model as opposed to a fresh corpus? Is there a huge error in my reasoning here?

**Comment by teaearlgraycold** [comment]
After scanning over the source code, it seems that building a `Chain` object it's too complex of a procedure (it should be `O(n)`) but it can be slow with large inputs.

However, loading a large JSON file into a dict is also `O(n)`, and slow with large inputs. You actually need to parse out more text when reading from a JSON file than when building the initial chain, since the JSON format of the `Text` object contains both the original text as well as the entire markov chain.

**Comment by ammgws** [comment]
With #50 you should see faster loading times for exported models (about 50% in my tests).

**Comment by jsvine** [comment]
#50 has been incorporated in to `v0.6.0`, which is now available via `pip`.
